apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: flask-app  # CHANGE THIS if you changed namespace.yaml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: IMAGE_NAME_PLACEHOLDER  # This will be replaced by Jenkins
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"