apiVersion: v1
kind: Service
metadata:
  name: flask-app
  namespace: flask-app  # CHANGE THIS if you changed namespace.yaml
spec:
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer